"""empty message

Revision ID: 399e958d44a2
Revises:
Create Date: 2021-06-25 20:10:11.706751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "399e958d44a2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "author",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_author_full_name"), "author", ["full_name"], unique=True)
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["author_id"], ["author.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name",
            "year",
            "author_id",
            deferrable="True",
            initially="DEFERRED",
            name="_books_uc",
        ),
    )
    op.create_index("_book_index", "book", ["name", "year", "author_id"], unique=False)
    op.create_index(op.f("ix_book_name"), "book", ["name"], unique=False)
    op.create_index(op.f("ix_book_year"), "book", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_year"), table_name="book")
    op.drop_index(op.f("ix_book_name"), table_name="book")
    op.drop_index("_book_index", table_name="book")
    op.drop_table("book")
    op.drop_index(op.f("ix_author_full_name"), table_name="author")
    op.drop_table("author")
    # ### end Alembic commands ###
