"""empty message

Revision ID: 79629a80b09f
Revises:
Create Date: 2021-06-27 20:40:56.610182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "79629a80b09f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
